<?php

/**
 * @file
 * Contains functions for Constructive Remote Data.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_theme().
 */
function constructive_remote_data_theme($existing, $type, $theme, $path) {

  // Set the views template to the template in this module.
  return [
    'views_view_unformatted__remote_posts' => [
      'template' => 'views-view-unformatted--remote-posts',
      'base hook' => 'views',
    ],
  ];

}
